# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7f9ac4921af049c2e379e7ea4c5e0fd36cac22557c58358222174038df36eca326e4cd5ed6033e160d4ee3d701edc4a3335f185be9691df566c3482ded8aed2

test:
  secret_key_base: 334c667f5b1c690634a1ebe7cfa720cf680c93f007381a37a5ed916e0bb373c8a444f67bec38f7d54215a7f3b40edaa5e76c23a573862e9b88e6a1c14d6e39b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
